spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/minicampus
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: cc127923@gmail.com
    password: lsfomiavcvibncdu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
